// Copyright (c) Oracle Corporation 2008.  All Rights Reserved.
//
// NAME
//    PrkdMsg.msg
//
// DESCRIPTION
//    Message file
//
// NOTES
//
//    MODIFIED    (MM/DD/YY)
//     mhbauer     08/13/02 - edit messages
//     jtellez     08/12/02 - Message Improvements
//     surchatt    02/08/01 - changing for OPS to ORAC name change
//     surchatt    07/20/00 - message file for the daemon
//     surchatt    07/20/00 - Creation
//  */
// 
// /**
//  *  @version $Header: PrkdMsg.java 13-aug-2002.11:37:37 mhbauer Exp $
//  *  @author  surchatt
//  *  @since   release specific (what release of product did this appear in)
//  */
// 
// PACKAGE=package oracle.ops.mgmt.resources;
// MSGIDTYPE=interface
3000, FAIL_INIT, "Failed to initialize and register with clusterware"
//  *Cause: 
// *Action: 
/
3001, READY_RCV_RQSTS, "Ready to receive client requests"
//  *Cause: 
// *Action: 
/
