/ 
/ $Header: pxerr.msg,v 1.3 93/12/22 11:03:09 jweisz: Exp $ 
/ 
/ Copyright (c) 1991 by Oracle Corporation 
/   NAME
/     pxerr.msg - Message file for SLAX run-time
/   DESCRIPTION
/     This file contains the fixed strings for all SLAX run-time instances.
/   NOTES
/     <other useful comments, qualifications, etc.>
/   MODIFIED   (MM/DD/YY)
/    jweisz     12/08/93 -  replace tabs with spaces (bug 142949)
/    tolkin     08/20/91 -         unsupported reserved word 
/    tolkin     08/14/91 -         Creation 
/
/  SLAX Error Messages
/
1,0,	"Fatal syntax error. Fix preceding errors and recompile."
2,0,	"Fatal error: insertion lied."
3,0,	"Internal error, impossible recovery procedure."
4,0,	"Fatal syntax error, unable to recover."
5,0,	"Fatal syntax error. Unable to recover before the end of the file."
6,0,	"Parser stack overflow error."
/
/ SLAX Fixed strings
/
101,0,	" etc.\n"
102,0,	" %s\n"
103,0,	"Encountered the symbol \"%s\" "
104,0,	"when expecting one of the following:\n"
105,0,	" was inserted before \"%s\" to continue.\n"
106,0,	"Replacing \"%s\" with \""
107,0,	"\".\n"
108,0,	"while parsing. Symbol was ignored.\n"
109,0,	" was assumed present to continue.\n"
110,0,	"The symbol \""
111,0,	"\" was ignored.\n"
112,0,	"\" was substituted for \"%s\" to continue.\n"
113,0,	"Resuming parse at line %d, column %d.\n"
114,0,	" etc.\n"
115,0,	"\n   "
116,0,	" %s"
117,0,	" \"%s\""
118,0,	"\n"
119,0,  "which is an unsupported reserved word.\n"

