/
/ Copyright (c) 1989, 2004, Oracle Corporation.  All Rights Reserved.
/
/ CONTENTS
/   Feedback messages for SQL*Plus
/
/ NOTES
/   The first column is the SQL*Plus message number.
/   The second column is reserved and must (for now) be 0.
/   The remainder of the line is the message text.
/
/
00000,0, "Operation %ld succeeded."
// *Cause:
// *Action:
00001,0, "Table created."
// *Cause:
// *Action:
00002,0, "Table created."
// *Cause:
// *Action:
00003,0, "1 row created."
// *Cause:
// *Action:
00004,0, "%ld rows created."
// *Cause:
// *Action:
00005,0, "1 row selected."
// *Cause:
// *Action:
00006,0, "%ld rows selected."
// *Cause:
// *Action:
00007,0, "Cluster created."
// *Cause:
// *Action:
00008,0, "Cluster created."
// *Cause:
// *Action:
00009,0, "Cluster altered."
// *Cause:
// *Action:
00010,0, "Cluster altered."
// *Cause:
// *Action:
00011,0, "1 row updated."
// *Cause:
// *Action:
00012,0, "%ld rows updated."
// *Cause:
// *Action:
00013,0, "1 row deleted."
// *Cause:
// *Action:
00014,0, "%ld rows deleted."
// *Cause:
// *Action:
00015,0, "Cluster dropped."
// *Cause:
// *Action:
00016,0, "Cluster dropped."
// *Cause:
// *Action:
00017,0, "Index created."
// *Cause:
// *Action:
00018,0, "Index created."
// *Cause:
// *Action:
00019,0, "Index dropped."
// *Cause:
// *Action:
00020,0, "Index dropped."
// *Cause:
// *Action:
00021,0, "Index altered."
// *Cause:
// *Action:
00022,0, "Index altered."
// *Cause:
// *Action:
00023,0, "Table dropped."
// *Cause:
// *Action:
00024,0, "Table dropped."
// *Cause:
// *Action:
00025,0, "Sequence created."
// *Cause:
// *Action:
00026,0, "Sequence created."
// *Cause:
// *Action:
00027,0, "Sequence altered."
// *Cause:
// *Action:
00028,0, "Sequence altered."
// *Cause:
// *Action:
00029,0, "Table altered."
// *Cause:
// *Action:
00030,0, "Table altered."
// *Cause:
// *Action:
00031,0, "Sequence dropped."
// *Cause:
// *Action:
00032,0, "Sequence dropped."
// *Cause:
// *Action:
00033,0, "Grant succeeded."
// *Cause:
// *Action:
00034,0, "Grant succeeded."
// *Cause:
// *Action:
00035,0, "Revoke succeeded."
// *Cause:
// *Action:
00036,0, "Revoke succeeded."
// *Cause:
// *Action:
00037,0, "Synonym created."
// *Cause:
// *Action:
00038,0, "Synonym created."
// *Cause:
// *Action:
00039,0, "Synonym dropped."
// *Cause:
// *Action:
00040,0, "Synonym dropped."
// *Cause:
// *Action:
00041,0, "View created."
// *Cause:
// *Action:
00042,0, "View created."
// *Cause:
// *Action:
00043,0, "View dropped."
// *Cause:
// *Action:
00044,0, "View dropped."
// *Cause:
// *Action:
00045,0, "Index validated."
// *Cause:
// *Action:
00046,0, "Index validated."
// *Cause:
// *Action:
00047,0, "Procedure created."
// *Cause:
// *Action:
00048,0, "Procedure created."
// *Cause:
// *Action:
00049,0, "Procedure altered."
// *Cause:
// *Action:
00050,0, "Procedure altered."
// *Cause:
// *Action:
00051,0, "Table(s) Locked."
// *Cause:
// *Action:
00052,0, "Table(s) Locked."
// *Cause:
// *Action:
00053,0, "Operation not supported in this system."
// *Cause:
// *Action:
00054,0, "Operation not supported in this system."
// *Cause:
// *Action:
00055,0, "Table renamed."
// *Cause:
// *Action:
00056,0, "Table renamed."
// *Cause:
// *Action:
00057,0, "Comment created."
// *Cause:
// *Action:
00058,0, "Comment created."
// *Cause:
// *Action:
00059,0, "Audit succeeded."
// *Cause:
// *Action:
00060,0, "Audit succeeded."
// *Cause:
// *Action:
00061,0, "Noaudit succeeded."
// *Cause:
// *Action:
00062,0, "Noaudit succeeded."
// *Cause:
// *Action:
00063,0, "Database link created."
// *Cause:
// *Action:
00064,0, "Database link created."
// *Cause:
// *Action:
00065,0, "Database link dropped."
// *Cause:
// *Action:
00066,0, "Database link dropped."
// *Cause:
// *Action:
00067,0, "Database created."
// *Cause:
// *Action:
00068,0, "Database created."
// *Cause:
// *Action:
00069,0, "Database altered."
// *Cause:
// *Action:
00070,0, "Database altered."
// *Cause:
// *Action:
00071,0, "Rollback segment created."
// *Cause:
// *Action:
00072,0, "Rollback segment created."
// *Cause:
// *Action:
00073,0, "Rollback segment altered."
// *Cause:
// *Action:
00074,0, "Rollback segment altered."
// *Cause:
// *Action:
00075,0, "Rollback segment dropped."
// *Cause:
// *Action:
00076,0, "Rollback segment dropped."
// *Cause:
// *Action:
00077,0, "Tablespace created."
// *Cause:
// *Action:
00078,0, "Tablespace created."
// *Cause:
// *Action:
00079,0, "Tablespace altered."
// *Cause:
// *Action:
00080,0, "Tablespace altered."
// *Cause:
// *Action:
00081,0, "Tablespace dropped."
// *Cause:
// *Action:
00082,0, "Tablespace dropped."
// *Cause:
// *Action:
00083,0, "Session altered."
// *Cause:
// *Action:
00084,0, "Session altered."
// *Cause:
// *Action:
00085,0, "User altered."
// *Cause:
// *Action:
00086,0, "User altered."
// *Cause:
// *Action:
00087,0, "Commit complete."
// *Cause:
// *Action:
00088,0, "Commit complete."
// *Cause:
// *Action:
00089,0, "Rollback complete."
// *Cause:
// *Action:
00090,0, "Rollback complete."
// *Cause:
// *Action:
00091,0, "Savepoint created."
// *Cause:
// *Action:
00092,0, "Savepoint created."
// *Cause:
// *Action:
00093,0, "PL/SQL procedure successfully completed."
// *Cause:
// *Action:
00094,0, "PL/SQL procedure successfully completed."
// *Cause:
// *Action:
00095,0, "Transaction set."
// *Cause:
// *Action:
00096,0, "Transaction set."
// *Cause:
// *Action:
00097,0, "System altered."
// *Cause:
// *Action:
00098,0, "System altered."
// *Cause:
// *Action:
00099,0, "Explained."
// *Cause:
// *Action:
00100, 0, "Explained."
// *Cause:
// *Action:
00101, 0, "User created."
// *Cause:
// *Action:
00102, 0, "User created."
// *Cause:
// *Action:
00103, 0, "Role created."
// *Cause:
// *Action:
00104, 0, "Role created."
// *Cause:
// *Action:
00105, 0, "User dropped."
// *Cause:
// *Action:
00106, 0, "User dropped."
// *Cause:
// *Action:
00107, 0, "Role dropped."
// *Cause:
// *Action:
00108, 0, "Role dropped."
// *Cause:
// *Action:
00109, 0, "Role set."
// *Cause:
// *Action:
00110, 0, "Role set."
// *Cause:
// *Action:
00111, 0, "Schema created."
// *Cause:
// *Action:
00112, 0, "Schema created."
// *Cause:
// *Action:
00113, 0, "Control file created."
// *Cause:
// *Action:
00114, 0, "Control file created."
// *Cause:
// *Action:
00115, 0, "Tracing altered."
// *Cause:
// *Action:
00116, 0, "Tracing altered."
// *Cause:
// *Action:
00117, 0, "Trigger created."
// *Cause:
// *Action:
00118, 0, "Trigger created."
// *Cause:
// *Action:
00119, 0, "Trigger altered."
// *Cause:
// *Action:
00120, 0, "Trigger altered."
// *Cause:
// *Action:
00121, 0, "Trigger dropped."
// *Cause:
// *Action:
00122, 0, "Trigger dropped."
// *Cause:
// *Action:
00123, 0, "Table analyzed."
// *Cause:
// *Action:
00124, 0, "Table analyzed."
// *Cause:
// *Action:
00125, 0, "Index analyzed."
// *Cause:
// *Action:
00126, 0, "Index analyzed."
// *Cause:
// *Action:
00127, 0, "Cluster analyzed."
// *Cause:
// *Action:
00128, 0, "Cluster analyzed."
// *Cause:
// *Action:
00129, 0, "Profile created."
// *Cause:
// *Action:
00130, 0, "Profile created."
// *Cause:
// *Action:
00131, 0, "Profile dropped."
// *Cause:
// *Action:
00132, 0, "Profile dropped."
// *Cause:
// *Action:
00133, 0, "Profile altered."
// *Cause:
// *Action:
00134, 0, "Profile altered."
// *Cause:
// *Action:
00135, 0, "Procedure dropped."
// *Cause:
// *Action:
00136, 0, "Procedure dropped."
// *Cause:
// *Action:
00139, 0, "Resource cost altered."
// *Cause:
// *Action:
00140, 0, "Resource cost altered."
// *Cause:
// *Action:
00141, 0, "Materialized view log created."
// *Cause:
// *Action:
00142, 0, "Materialized view log created."
// *Cause:
// *Action:
00143, 0, "Materialized view log altered."
// *Cause:
// *Action:
00144, 0, "Materialized view log altered."
// *Cause:
// *Action:
00145, 0, "Materialized view log dropped."
// *Cause:
// *Action:
00146, 0, "Materialized view log dropped."
// *Cause:
// *Action:
00147, 0, "Materialized view created."
// *Cause:
// *Action:
00148, 0, "Materialized view created."
// *Cause:
// *Action:
00149, 0, "Materialized view altered."
// *Cause:
// *Action:
00150, 0, "Materialized view altered."
// *Cause:
// *Action:
00151, 0, "Materialized view dropped."
// *Cause:
// *Action:
00152, 0, "Materialized view dropped."
// *Cause:
// *Action:
00153, 0, "Type created."
// *Cause:
// *Action:
00154, 0, "Type created."
// *Cause:
// *Action:
00155, 0, "Type dropped."
// *Cause:
// *Action:
00156, 0, "Type dropped."
// *Cause:
// *Action:
00157, 0, "Role altered."
// *Cause:
// *Action:
00158, 0, "Role altered."
// *Cause:
// *Action:
00159, 0, "Type altered."
// *Cause:
// *Action:
00160, 0, "Type altered."
// *Cause:
// *Action:
00161, 0, "Type body created."
// *Cause:
// *Action:
00162, 0, "Type body created."
// *Cause:
// *Action:
00163, 0, "Type body altered."
// *Cause:
// *Action:
00164, 0, "Type body altered."
// *Cause:
// *Action:
00165, 0, "Type body dropped."
// *Cause:
// *Action:
00166, 0, "Type body dropped."
// *Cause:
// *Action:
00167, 0, "Library dropped."
// *Cause:
// *Action:
00168, 0, "Library dropped."
// *Cause:
// *Action:
00169, 0, "Table truncated."
// *Cause:
// *Action:
00170, 0, "Table truncated."
// *Cause:
// *Action:
00171, 0, "Cluster truncated."
// *Cause:
// *Action:
00172, 0, "Cluster truncated."
// *Cause:
// *Action:
00175, 0, "View altered."
// *Cause:
// *Action:
00176, 0, "View altered."
// *Cause:
// *Action:
00179, 0, "Constraint set."
// *Cause:
// *Action:
00180, 0, "Constraint set."
// *Cause:
// *Action:
00181, 0, "Function created."
// *Cause:
// *Action:
00182, 0, "Function created."
// *Cause:
// *Action:
00183, 0, "Function altered."
// *Cause:
// *Action:
00184, 0, "Function altered."
// *Cause:
// *Action:
00185, 0, "Function dropped."
// *Cause:
// *Action:
00186, 0, "Function dropped."
// *Cause:
// *Action:
00187, 0, "Package created."
// *Cause:
// *Action:
00188, 0, "Package created."
// *Cause:
// *Action:
00189, 0, "Package altered."
// *Cause:
// *Action:
00190, 0, "Package altered."
// *Cause:
// *Action:
00191, 0, "Package dropped."
// *Cause:
// *Action:
00192, 0, "Package dropped."
// *Cause:
// *Action:
00193, 0, "Package body created."
// *Cause:
// *Action:
00194, 0, "Package body created."
// *Cause:
// *Action:
00195, 0, "Package body altered."
// *Cause:
// *Action:
00196, 0, "Package body altered."
// *Cause:
// *Action:
00197, 0, "Package body dropped."
// *Cause:
// *Action:
00198, 0, "Package body dropped."
// *Cause:
// *Action:
00225, 0, "Warning: Procedure created with compilation errors."
// *Cause:
// *Action:
00226, 0, "Warning: Procedure altered with compilation errors."
// *Cause:
// *Action:
00227, 0, "Warning: Function created with compilation errors."
// *Cause:
// *Action:
00228, 0, "Warning: Function altered with compilation errors."
// *Cause:
// *Action:
00229, 0, "Warning: Package created with compilation errors."
// *Cause:
// *Action:
00230, 0, "Warning: Package altered with compilation errors."
// *Cause:
// *Action:
00231, 0, "Warning: Package Body created with compilation errors."
// *Cause:
// *Action:
00232, 0, "Warning: Package Body altered with compilation errors."
// *Cause:
// *Action:
00233, 0, "Warning: View created with compilation errors."
// *Cause:
// *Action:
00234, 0, "Warning: View altered with compilation errors."
// *Cause:
// *Action:
00235, 0, "Warning: Trigger created with compilation errors."
// *Cause:
// *Action:
00236, 0, "Warning: Trigger altered with compilation errors."
// *Cause:
// *Action:
00237, 0, "Warning: Type created with compilation errors."
// *Cause:
// *Action:
00238, 0, "Warning: Type altered with compilation errors."
// *Cause:
// *Action:
00239, 0, "Warning: Type Body created with compilation errors."
// *Cause:
// *Action:
00240, 0, "Warning: Type Body altered with compilation errors."
// *Cause:
// *Action:
00250, 0, "Warning: Library created with compilation errors."
// *Cause:
// *Action:
00251, 0, "Warning: Library altered with compilation errors."
// *Cause:
// *Action:
00252, 0, "Warning: Java created with compilation errors."
// *Cause:
// *Action:
00253, 0, "Warning: Java altered with compilation errors."
// *Cause:
// *Action:
00254, 0, "Warning: PL/SQL compilation errors."
// *Cause:
// *Action:
00255, 0, "Warning: Dimension created with compilation errors."
// *Cause:
// *Action:
00256, 0, "Warning: Dimension altered with compilation errors."
// *Cause:
// *Action:
// *Action:
00257, 0, "Warning: Assembly created with compilation errors."
// *Cause:
// *Action:
00258, 0, "Warning: Assembly altered with compilation errors."
// *Cause:
// *Action:
00313, 0, "Directory created."
// *Cause:
// *Action:
00314, 0, "Directory created."
// *Cause:
// *Action:
00315, 0, "Directory dropped."
// *Cause:
// *Action:
00316, 0, "Directory dropped."
// *Cause:
// *Action:
00317, 0, "Library created."
// *Cause:
// *Action:
00318, 0, "Library created."
// *Cause:
// *Action:
00319, 0, "Java created."
// *Cause:
// *Action:
00320, 0, "Java created."
// *Cause:
// *Action:
00321, 0, "Java altered."
// *Cause:
// *Action:
00322, 0, "Java altered."
// *Cause:
// *Action:
00323, 0, "Java dropped."
// *Cause:
// *Action:
00324, 0, "Java dropped."
// *Cause:
// *Action:
00325, 0, "Operator created."
// *Cause:
// *Action:
00326, 0, "Operator created."
// *Cause:
// *Action:
00327, 0, "Indextype created."
// *Cause:
// *Action:
00328, 0, "Indextype created."
// *Cause:
// *Action:
00329, 0, "Indextype dropped."
// *Cause:
// *Action:
00330, 0, "Indextype dropped."
// *Cause:
// *Action:
00331, 0, "Indextype altered."
// *Cause:
// *Action:
00332, 0, "Indextype altered."
// *Cause:
// *Action:
00333, 0, "Operator dropped."
// *Cause:
// *Action:
00334, 0, "Operator dropped."
// *Cause:
// *Action:
00335, 0, "Statistics associated."
// *Cause:
// *Action:
00336, 0, "Statistics associated."
// *Cause:
// *Action:
00337, 0, "Statistics disassociated."
// *Cause:
// *Action:
00338, 0, "Statistics disassociated."
// *Cause:
// *Action:
00339, 0, "Call completed."
// *Cause:
// *Action:
00340, 0, "Call completed."
// *Cause:
// *Action:
00341, 0, "Summary created."
// *Cause:
// *Action:
00342, 0, "Summary created."
// *Cause:
// *Action:
00343, 0, "Summary altered."
// *Cause:
// *Action:
00344, 0, "Summary altered."
// *Cause:
// *Action:
00345, 0, "Summary dropped."
// *Cause:
// *Action:
00346, 0, "Summary dropped."
// *Cause:
// *Action:
00347, 0, "Dimension created."
// *Cause:
// *Action:
00348, 0, "Dimension created."
// *Cause:
// *Action:
00349, 0, "Dimension altered."
// *Cause:
// *Action:
00350, 0, "Dimension altered."
// *Cause:
// *Action:
00351, 0, "Dimension dropped."
// *Cause:
// *Action:
00352, 0, "Dimension dropped."
// *Cause:
// *Action:
00353, 0, "Context created."
// *Cause:
// *Action:
00354, 0, "Context created."
// *Cause:
// *Action:
00355, 0, "Context dropped."
// *Cause:
// *Action:
00356, 0, "Context dropped."
// *Cause:
// *Action:
00357, 0, "Outline altered."
// *Cause:
// *Action:
00358, 0, "Outline altered."
// *Cause:
// *Action:
00359, 0, "Outline created."
// *Cause:
// *Action:
00360, 0, "Outline created."
// *Cause:
// *Action:
00361, 0, "Outline dropped."
// *Cause:
// *Action:
00362, 0, "Outline dropped."
// *Cause:
// *Action:
00365, 0, "Operator altered."
// *Cause:
// *Action:
00366, 0, "Operator altered."
// *Cause:
// *Action:
00367, 0, "Database Link altered."
// *Comment: This message was created for earlier release but was removed
//           in later release. A new message 449 and 450 has been introduced
// *Cause:
// *Action:
00368, 0, "Database Link altered."
// *Comment: This message was created for earlier release but was removed
//           in later release. A new message 449 and 450 has been introduced
// *Cause:
// *Action:
00373, 0, "File created."
// *Cause:
// *Action:
00374, 0, "File created."
// *Cause:
// *Action:
00375, 0, "File created."
// *Cause:
// *Action:
00376, 0, "File created."
// *Cause:
// *Action:
00377, 0, "1 row merged."
// *Cause:
// *Action:
00378, 0, "%ld rows merged."
// *Cause:
// *Action:
00383, 0, "Synonym altered."
// *Cause:
// *Action:
00384, 0, "Synonym altered."
// *Cause:
// *Action:
00385, 0, "Diskgroup altered."
// *Cause:
// *Action:
00386, 0, "Diskgroup altered."
// *Cause:
// *Action:
00387, 0, "Diskgroup created."
// *Cause:
// *Action:
00388, 0, "Diskgroup created."
// *Cause:
// *Action:
00389, 0, "Diskgroup dropped."
// *Cause:
// *Action:
00390, 0, "Diskgroup dropped."
// *Cause:
// *Action:
00391, 0, "Library altered."
// *Cause:
// *Action:
00392, 0, "Library altered."
// *Cause:
// *Action:
00393, 0, "Recyclebin purged."
// *Cause:
// *Action:
00394, 0, "Recyclebin purged."
// *Cause:
// *Action:
00395, 0, "DBA Recyclebin purged."
// *Cause:
// *Action:
00396, 0, "DBA Recyclebin purged."
// *Cause:
// *Action:
00397, 0, "Tablespace purged."
// *Cause:
// *Action:
00398, 0, "Tablespace purged."
// *Cause:
// *Action:
00399, 0, "Table purged."
// *Cause:
// *Action:
00400, 0, "Table purged."
// *Cause:
// *Action:
00401, 0, "Index purged."
// *Cause:
// *Action:
00402, 0, "Index purged."
// *Cause:
// *Action:
00403, 0, "Flashback complete."
// *Cause:
// *Action:
00404, 0, "Flashback complete."
// *Cause:
// *Action:
00405, 0, "Database dropped."
// *Cause:
// *Action:
00406, 0, "Database dropped."
// *Cause:
// *Action:
00407, 0, "Flashback complete."
// *Cause:
// *Action:
00408, 0, "Flashback complete."
// *Cause:
// *Action:
00409, 0, "Flashback complete."
// *Cause:
// *Action:
00410, 0, "Flashback complete."
// *Cause:
// *Action:
00411, 0, "Restore point created."
// *Cause:
// *Action:
00412, 0, "Restore point created."
// *Cause:
// *Action:
00413, 0, "Restore point dropped."
// *Cause:
// *Action:
00414, 0, "Restore point dropped."
// *Cause:
// *Action:
00423, 0, "Edition created."
// *Cause:
// *Action:
00424, 0, "Edition created."
// *Cause:
// *Action:
00425, 0, "Edition altered."
// *Cause:
// *Action:
00426, 0, "Edition altered."
// *Cause:
// *Action:
00427, 0, "Edition dropped."
// *Cause:
// *Action:
00428, 0, "Edition dropped."
// *Cause:
// *Action:
00429, 0, "Assembly dropped."
// *Cause:
// *Action:
00430, 0, "Assembly dropped."
// *Cause:
// *Action:
00431, 0, "Assembly created."
// *Cause:
// *Action:
00432, 0, "Assembly created."
// *Cause:
// *Action:
00433, 0, "Assembly altered."
// *Cause:
// *Action:
00434, 0, "Assembly altered."
// *Cause:
// *Action:
00435, 0, "Flashback archive created."
// *Cause:
// *Action:
00436, 0, "Flashback archive created."
// *Cause:
// *Action:
00437, 0, "Flashback archive altered."
// *Cause:
// *Action:
00438, 0, "Flashback archive altered."
// *Cause:
// *Action:
00439, 0, "Flashback archive dropped."
// *Cause:
// *Action:
00440, 0, "Flashback archive dropped."
// *Cause:
// *Action:
00441, 0, "Schema altered."
// *Cause:
// *Action:
00442, 0, "Schema altered."
// *Cause:
// *Action:
00443, 0, "Schema synonym created."
// *Cause:
// *Action:
00444, 0, "Schema synonym created."
// *Cause:
// *Action:
00445, 0, "Schema synonym altered."
// *Cause:
// *Action:
00446, 0, "Schema synonym altered."
// *Cause:
// *Action:
00447, 0, "Schema synonym dropped."
// *Cause:
// *Action:
00448, 0, "Schema synonym dropped."
// *Cause:
// *Action:
00449, 0, "Database link altered."
// *Comment: This is the same message as 367 and 368. The creation of this
//           message is because the 367 and 368 was removed and can not be 
//           reused.
// *Cause:
// *Action:
00450, 0, "Database link altered."
// *Comment: This is the same message as 367 and 368. The creation of this
//           message is because the 367 and 368 was removed and can not be 
//           reused.
// *Cause:
// *Action:
09325,0, "%s rows created."
// *Comment: This temporary message is introduced to avoid large number of
//           difs in rdbms while message number  4  is being translated to 
//           resolve bug  7047565. It will be removed once we have the new
//           transacted message for message number 4.
// *Cause:
// *Action:
